### ISSUE TITLE
Update to use EDD's build in license handler

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-license-free-download#1]

**Comment by robincornett** [comment]
Note: the current version of the plugin is using version 1.6 of the `EDD_SL_Plugin_Updater` class and is causing this warning:

`PHP Warning:  Creating default object from empty value in ...\edd-license-free-download\includes\EDD_SL_Plugin_Updater.php on line 85`

Since this issue is already open here, I assume the warning would be resolved as part of resolving this.
